title: Workshop in Molecular Evolution
director: Paul O. Lewis
codirector: Peter Beerli
logo_filename: tshirt-2019.png
email: moledirector@mbl.edu
description: >-
  Since 1988, the Workshop in Molecular Evolution at Woods Hole has 
  provided essential training in the theory and methods of molecular evolution.
#baseurl: "/people/plewis/wh2020"
baseurl: ""
url: ""
#twitter_username: jekyllrb
facebook_username: Molecular Evolution Workshop at the MBL
#github_username:  molevolworkshop
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
