title: Molecular Evolution Workshop (Woods Hole)
email: moledirector@mbl.edu
description: >-
  Founded in 1988, the Workshop in Molecular Evolution at the Woods Hole Marine
  Biological Laboratory is the longest-running workshop of its kind, and it has 
  earned worldwide recognition for its rich and intensive learning experience.
baseurl: ""
url: ""
#twitter_username: jekyllrb
github_username:  molevolworkshop

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
